import { Case } from "./types";

export const sampleCases: Case[] = [
  {
    id: "case-001",
    zaaknummer: "BZ-2024-0042",
    bezwaarmaker: "J.A. van der Berg",
    status: "🟠 In afwachting informele afhandeling",
    fase: "Informeel",
    datumOntvangst: "2024-03-01",
    datumBesluit: "2024-01-15",
    einddatumBezwaartermijn: "2024-02-26",
    beslistermijn12Weken: "2024-05-20",
    verdaagd: "Ja",
    beslistermijnNaVerdaging: "2024-07-01",
    volgendeActie: "Check vakafdeling",
    actiedatum: "2024-03-15",
    datumHoorzitting: "",
    adviesUitgebracht: "Nee",
    datumAdvies: "",
    beslissingOpBezwaar: "Nee",
    datumBeslissingOpBezwaar: "",
    aantekeningen: "Bezwaar ingediend tegen afwijzing omgevingsvergunning. Bezwaarmaker wil uitbreiding bijgebouw.",
  },
  {
    id: "case-002",
    zaaknummer: "BZ-2024-0058",
    bezwaarmaker: "Stichting Buurtbelang Noord",
    status: "🔵 Zitting gepland",
    fase: "Zitting",
    datumOntvangst: "2024-02-14",
    datumBesluit: "2024-01-01",
    einddatumBezwaartermijn: "2024-02-12",
    beslistermijn12Weken: "2024-05-07",
    verdaagd: "Nee",
    beslistermijnNaVerdaging: "",
    volgendeActie: "Uitnodigingen versturen",
    actiedatum: "2024-03-20",
    datumHoorzitting: "2024-04-03",
    adviesUitgebracht: "Nee",
    datumAdvies: "",
    beslissingOpBezwaar: "Nee",
    datumBeslissingOpBezwaar: "",
    aantekeningen: "Collectief bezwaar namens 12 bewoners tegen bouwplan wooncomplex.",
  },
  {
    id: "case-003",
    zaaknummer: "BZ-2024-0071",
    bezwaarmaker: "M.P. Janssen",
    status: "🔴 In afwachting herstel",
    fase: "Intake",
    datumOntvangst: "2024-03-10",
    datumBesluit: "2024-02-01",
    einddatumBezwaartermijn: "2024-03-14",
    beslistermijn12Weken: "2024-06-06",
    verdaagd: "Nee",
    beslistermijnNaVerdaging: "",
    volgendeActie: "Controleer hersteltermijn",
    actiedatum: "2024-03-24",
    datumHoorzitting: "",
    adviesUitgebracht: "Nee",
    datumAdvies: "",
    beslissingOpBezwaar: "Nee",
    datumBeslissingOpBezwaar: "",
    aantekeningen: "Bezwaar ontvolledig ingediend. Herstelverzuimbrief verstuurd op 10-03-2024.",
  },
  {
    id: "case-004",
    zaaknummer: "BZ-2024-0035",
    bezwaarmaker: "B.J. de Groot",
    status: "🟣 Advies verzonden",
    fase: "Afronding",
    datumOntvangst: "2024-01-20",
    datumBesluit: "2023-12-05",
    einddatumBezwaartermijn: "2024-01-16",
    beslistermijn12Weken: "2024-04-09",
    verdaagd: "Ja",
    beslistermijnNaVerdaging: "2024-05-21",
    volgendeActie: "Wachten op beslissing op bezwaar",
    actiedatum: "2024-05-21",
    datumHoorzitting: "2024-03-05",
    adviesUitgebracht: "Ja",
    datumAdvies: "2024-03-20",
    beslissingOpBezwaar: "Nee",
    datumBeslissingOpBezwaar: "",
    aantekeningen: "Bezwaar gegrond verklaard in concept advies. Wachten op definitieve beslissing bestuursorgaan.",
  },
  {
    id: "case-005",
    zaaknummer: "BZ-2024-0019",
    bezwaarmaker: "N.L. Bakker",
    status: "⚫ Afgerond",
    fase: "Afronding",
    datumOntvangst: "2024-01-05",
    datumBesluit: "2023-11-20",
    einddatumBezwaartermijn: "2024-01-01",
    beslistermijn12Weken: "2024-03-26",
    verdaagd: "Nee",
    beslistermijnNaVerdaging: "",
    volgendeActie: "Geen",
    actiedatum: "",
    datumHoorzitting: "2024-02-08",
    adviesUitgebracht: "Ja",
    datumAdvies: "2024-02-22",
    beslissingOpBezwaar: "Ja",
    datumBeslissingOpBezwaar: "2024-03-10",
    aantekeningen: "Bezwaar ongegrond verklaard. Zaak volledig afgerond.",
  },
];
